spring.application.name=url
spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=url-shortener-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Tell Spring which type to expect
spring.kafka.consumer.properties.spring.json.value.default.type=com.shortner.url.DTO.UrlClickEvent

# Allow deserialization from your package
spring.kafka.consumer.properties.spring.json.trusted.packages=com.shortner.url.DTO

#logging.level.org.springframework.kafka=DEBUG
#logging.level.org.apache.kafka=DEBUG

management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
